version: '3.8'

services:
  mongo:
    env_file: .env
    image: mongo:latest
    container_name: ${DB_SERVER}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:${DB_PORT}
    volumes:
      - ./docker/mongo/var/pokemon.JSON:/var/pokemon.JSON
      - ./docker/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/1.js
      - ./docker/mongo/docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/2.sh

  web:
    env_file: .env
    build: .
    container_name: ${WEB_SERVER}
    ports:
      - 3000:${WEB_PORT}
