version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/var/pokemon.JSON:/var/pokemon.JSON
      - ./docker/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/1.js
      - ./docker/mongo/docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/2.sh

  #webserver:
  #  build: ./
  #  stdin_open: true
  #  tty: true
  #  ports:
  #    - 3000:3000
